# This is a basic workflow to help you get started with Actions

name: Github Actions CI to build pdf from tex source.

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: Resume.tex

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          pre_compile: tlmgr update --self && tlmgr update --all

          # Arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: latexmk -c

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

      - name: Check pdf file
        run: |
          file Resume.pdf | grep -q ' PDF '
  
      - name: Upload file to repository
        run: |
          git config --global user.name "Naveen015"
          git config --global user.email "gnaveen1509@gmail.com"
          git add Resume.pdf
          git commit -m "Updated Resume"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
